# One nginx worker process per CPU core.
worker_processes auto;

# Mandatory events block.
# Each worker process can handle up to N simultaneous connections.
events {
  worker_connections 4096;
}

http{
  #define a named upstream group of backend servers

  #docker's internal DNS resolves "keyservice" to all running replicals

  #ngic round roubins between them

  upstream keyservice_backend{
    server keyservice:8080;
    keepalive 32; # pool of up to 32 idle connections per nginx worker
  }



# logging information to see load balancing in action
log_format upstream_log '$remote_addr - "$request" '
                            '$status upstream=$upstream_addr '
                            'rt=${request_time}s';

access_log /var/log/nginx/access.log upstream_log;


server{
  listen 80;
  #Listen on port 80, and for every URL path, forward to the upstream group.

  #send every request to the upstream group 

  location / {
    proxy_pass http://keyservice_backend;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
}
