apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    uid: postgres
    url: postgres:5432
    user: mint
    jsonData:
      database: mint
      sslmode: disable
    secureJsonData:
      password: mint_dev
